name: Daily Update
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - uses: actions/checkout@v2

      - name: run download and split
        run: ./run_job.sh run

      - name: update repo
        run: ./moviewatcher.sh gha:update
