name: Daily Update
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        name: Cache downloads
        with:
          path: ./tmp
          key: ${{ runner.os }}-downloads
          restore-keys: |
            ${{ runner.os }}-downloads

      - name: run download and split
        run: ./run_job.sh run

      - name: update repo
        run: ./moviewatcher.sh gha:update
